package co.uk.silvania.advancedarmoury.items;

import co.uk.silvania.advancedarmoury.gun.prebuilt.M4CarbinePolymer;
import co.uk.silvania.advancedarmoury.items.components.asset.Receiver;
import co.uk.silvania.advancedarmoury.items.components.asset.internal.M4FrontEnd;
import co.uk.silvania.advancedarmoury.items.components.asset.internal.M4Receiver;
import co.uk.silvania.advancedarmoury.items.components.asset.internal.M4Stock;
import co.uk.silvania.advancedarmoury.items.components.generic.assault.ItemAssaultBolt;
import co.uk.silvania.advancedarmoury.items.components.generic.assault.ItemAssaultBoltCarrier;
import co.uk.silvania.advancedarmoury.items.components.generic.assault.ItemAssaultBoltPart;
import co.uk.silvania.advancedarmoury.items.components.generic.assault.ItemAssaultChamber;
import co.uk.silvania.advancedarmoury.items.components.generic.assault.ItemAssaultChargingHandle;
import co.uk.silvania.advancedarmoury.items.components.generic.assault.ItemAssaultEjector;
import co.uk.silvania.advancedarmoury.items.components.generic.assault.ItemAssaultExtractor;
import co.uk.silvania.advancedarmoury.items.components.generic.assault.ItemAssaultFiringPin;
import co.uk.silvania.advancedarmoury.items.components.generic.assault.ItemAssaultFiringPinRetainerPin;
import co.uk.silvania.advancedarmoury.items.components.generic.assault.ItemAssaultGasChamber;
import co.uk.silvania.advancedarmoury.items.components.generic.assault.ItemAssaultGasFeed;
import co.uk.silvania.advancedarmoury.items.components.generic.assault.ItemAssaultPiston;
import co.uk.silvania.advancedarmoury.items.components.generic.assault.ItemAssaultPistonChamber;
import co.uk.silvania.advancedarmoury.items.components.generic.assault.ItemAssaultSpring;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.item.Item;

public class AAItemAssaultComponents {

	public static Item assaultBoltGold;
	public static Item assaultBoltIron;
	public static Item assaultBoltBronze;
	public static Item assaultBoltTitanium;
	public static Item assaultBoltAluminium;
	public static Item assaultBoltSteel;
	public static Item assaultBoltPolymer;
	public static Item assaultBoltMythian;
	public static Item assaultBoltPromethium;
	public static Item assaultBoltSarinum;
	public static Item assaultBoltVelerium;
	public static Item assaultBoltCelibras;
	public static Item assaultBoltAericas;
	public static Item assaultBoltDarisin;
	
	public static Item assaultBoltCarrierGold;
	public static Item assaultBoltCarrierIron;
	public static Item assaultBoltCarrierBronze;
	public static Item assaultBoltCarrierTitanium;
	public static Item assaultBoltCarrierAluminium;
	public static Item assaultBoltCarrierSteel;
	public static Item assaultBoltCarrierPolymer;
	public static Item assaultBoltCarrierMythian;
	public static Item assaultBoltCarrierPromethium;
	public static Item assaultBoltCarrierSarinum;
	public static Item assaultBoltCarrierVelerium;
	public static Item assaultBoltCarrierCelibras;	
	public static Item assaultBoltCarrierAericas;
	public static Item assaultBoltCarrierDarisin;
	
	public static Item assaultChargingHandleGold;
	public static Item assaultChargingHandleIron;
	public static Item assaultChargingHandleBronze;
	public static Item assaultChargingHandleTitanium;
	public static Item assaultChargingHandleAluminium;
	public static Item assaultChargingHandleSteel;
	public static Item assaultChargingHandlePolymer;
	public static Item assaultChargingHandleMythian;
	public static Item assaultChargingHandlePromethium;
	public static Item assaultChargingHandleSarinum;
	public static Item assaultChargingHandleVelerium;
	public static Item assaultChargingHandleCelibras;
	public static Item assaultChargingHandleAericas;
	public static Item assaultChargingHandleDarisin;
	
	public static Item assaultEjectorGold;
	public static Item assaultEjectorIron;
	public static Item assaultEjectorBronze;
	public static Item assaultEjectorTitanium;
	public static Item assaultEjectorAluminium;
	public static Item assaultEjectorSteel;
	public static Item assaultEjectorPolymer;
	public static Item assaultEjectorMythian;
	public static Item assaultEjectorPromethium;
	public static Item assaultEjectorSarinum;
	public static Item assaultEjectorVelerium;
	public static Item assaultEjectorCelibras;
	public static Item assaultEjectorAericas;
	public static Item assaultEjectorDarisin;
	
	public static Item assaultExtractorGold;
	public static Item assaultExtractorIron;
	public static Item assaultExtractorBronze;
	public static Item assaultExtractorTitanium;
	public static Item assaultExtractorAluminium;
	public static Item assaultExtractorSteel;
	public static Item assaultExtractorPolymer;
	public static Item assaultExtractorMythian;
	public static Item assaultExtractorPromethium;
	public static Item assaultExtractorSarinum;
	public static Item assaultExtractorVelerium;
	public static Item assaultExtractorCelibras;
	public static Item assaultExtractorAericas;
	public static Item assaultExtractorDarisin;
	
	public static Item assaultFiringPinGold;
	public static Item assaultFiringPinIron;
	public static Item assaultFiringPinBronze;
	public static Item assaultFiringPinTitanium;
	public static Item assaultFiringPinAluminium;
	public static Item assaultFiringPinSteel;
	public static Item assaultFiringPinPolymer;
	public static Item assaultFiringPinMythian;
	public static Item assaultFiringPinPromethium;
	public static Item assaultFiringPinSarinum;
	public static Item assaultFiringPinVelerium;
	public static Item assaultFiringPinCelibras;
	public static Item assaultFiringPinAericas;
	public static Item assaultFiringPinDarisin;
	
	public static Item assaultFiringPinRetainerPinGold;
	public static Item assaultFiringPinRetainerPinIron;
	public static Item assaultFiringPinRetainerPinBronze;
	public static Item assaultFiringPinRetainerPinTitanium;
	public static Item assaultFiringPinRetainerPinAluminium;
	public static Item assaultFiringPinRetainerPinSteel;
	public static Item assaultFiringPinRetainerPinPolymer;
	public static Item assaultFiringPinRetainerPinMythian;
	public static Item assaultFiringPinRetainerPinPromethium;
	public static Item assaultFiringPinRetainerPinSarinum;
	public static Item assaultFiringPinRetainerPinVelerium;
	public static Item assaultFiringPinRetainerPinCelibras;
	public static Item assaultFiringPinRetainerPinAericas;
	public static Item assaultFiringPinRetainerPinDarisin;
	
	public static Item assaultPistonGold;
	public static Item assaultPistonIron;
	public static Item assaultPistonBronze;
	public static Item assaultPistonTitanium;
	public static Item assaultPistonAluminium;
	public static Item assaultPistonSteel;
	public static Item assaultPistonPolymer;
	public static Item assaultPistonMythian;
	public static Item assaultPistonPromethium;
	public static Item assaultPistonSarinum;
	public static Item assaultPistonVelerium;
	public static Item assaultPistonCelibras;
	public static Item assaultPistonAericas;
	public static Item assaultPistonDarisin;
	
	public static Item assaultSpringGold;
	public static Item assaultSpringIron;
	public static Item assaultSpringBronze;
	public static Item assaultSpringTitanium;
	public static Item assaultSpringAluminium;
	public static Item assaultSpringSteel;
	public static Item assaultSpringPolymer;
	public static Item assaultSpringMythian;
	public static Item assaultSpringPromethium;
	public static Item assaultSpringSarinum;
	public static Item assaultSpringVelerium;
	public static Item assaultSpringCelibras;
	public static Item assaultSpringAericas;
	public static Item assaultSpringDarisin;
	
	public static Item assaultPistonChamberGold;
	public static Item assaultPistonChamberIron;
	public static Item assaultPistonChamberBronze;
	public static Item assaultPistonChamberTitanium;
	public static Item assaultPistonChamberAluminium;
	public static Item assaultPistonChamberSteel;
	public static Item assaultPistonChamberPolymer;
	public static Item assaultPistonChamberMythian;
	public static Item assaultPistonChamberPromethium;
	public static Item assaultPistonChamberSarinum;
	public static Item assaultPistonChamberVelerium;
	public static Item assaultPistonChamberCelibras;
	public static Item assaultPistonChamberAericas;
	public static Item assaultPistonChamberDarisin;
	
	public static Item assaultGasChamberGold;
	public static Item assaultGasChamberIron;
	public static Item assaultGasChamberBronze;
	public static Item assaultGasChamberTitanium;
	public static Item assaultGasChamberAluminium;
	public static Item assaultGasChamberSteel;
	public static Item assaultGasChamberPolymer;
	public static Item assaultGasChamberMythian;
	public static Item assaultGasChamberPromethium;
	public static Item assaultGasChamberSarinum;
	public static Item assaultGasChamberVelerium;
	public static Item assaultGasChamberCelibras;
	public static Item assaultGasChamberAericas;
	public static Item assaultGasChamberDarisin;
	
	public static Item assaultGasFeedGold;
	public static Item assaultGasFeedIron;
	public static Item assaultGasFeedBronze;
	public static Item assaultGasFeedTitanium;
	public static Item assaultGasFeedAluminium;
	public static Item assaultGasFeedSteel;
	public static Item assaultGasFeedPolymer;
	public static Item assaultGasFeedMythian;
	public static Item assaultGasFeedPromethium;
	public static Item assaultGasFeedSarinum;
	public static Item assaultGasFeedVelerium;
	public static Item assaultGasFeedCelibras;
	public static Item assaultGasFeedAericas;
	public static Item assaultGasFeedDarisin;
	
	public static Item assaultChamberGold;
	public static Item assaultChamberIron;
	public static Item assaultChamberBronze;
	public static Item assaultChamberTitanium;
	public static Item assaultChamberAluminium;
	public static Item assaultChamberSteel;
	public static Item assaultChamberPolymer;
	public static Item assaultChamberMythian;
	public static Item assaultChamberPromethium;
	public static Item assaultChamberSarinum;
	public static Item assaultChamberVelerium;
	public static Item assaultChamberCelibras;
	public static Item assaultChamberAericas;
	public static Item assaultChamberDarisin;
	
	public static Item assaultReceiverM4Gold;
	public static Item assaultReceiverM4Iron;
	public static Item assaultReceiverM4Bronze;
	public static Item assaultReceiverM4Titanium;
	public static Item assaultReceiverM4Aluminium;
	public static Item assaultReceiverM4Steel;
	public static Item assaultReceiverM4Polymer;
	public static Item assaultReceiverM4Mythian;
	public static Item assaultReceiverM4Promethium;
	public static Item assaultReceiverM4Sarinum;
	public static Item assaultReceiverM4Velerium;
	public static Item assaultReceiverM4Celibras;
	public static Item assaultReceiverM4Aericas;
	public static Item assaultReceiverM4Darisin;
	
	public static Item assaultFrontEndM4Gold;
	public static Item assaultFrontEndM4Iron;
	public static Item assaultFrontEndM4Bronze;
	public static Item assaultFrontEndM4Titanium;
	public static Item assaultFrontEndM4Aluminium;
	public static Item assaultFrontEndM4Steel;
	public static Item assaultFrontEndM4Polymer;
	public static Item assaultFrontEndM4Mythian;
	public static Item assaultFrontEndM4Promethium;
	public static Item assaultFrontEndM4Sarinum;
	public static Item assaultFrontEndM4Velerium;
	public static Item assaultFrontEndM4Celibras;
	public static Item assaultFrontEndM4Aericas;
	public static Item assaultFrontEndM4Darisin;
	
	public static Item assaultStockM4Gold;
	public static Item assaultStockM4Iron;
	public static Item assaultStockM4Bronze;
	public static Item assaultStockM4Titanium;
	public static Item assaultStockM4Aluminium;
	public static Item assaultStockM4Steel;
	public static Item assaultStockM4Polymer;
	public static Item assaultStockM4Mythian;
	public static Item assaultStockM4Promethium;
	public static Item assaultStockM4Sarinum;
	public static Item assaultStockM4Velerium;
	public static Item assaultStockM4Celibras;
	public static Item assaultStockM4Aericas;
	public static Item assaultStockM4Darisin;
	
	public static void init() {
		assaultComponents();
		registerItems();
	}
	
	public static void assaultComponents() {
		// ARGS:
		//Part Name, Tag colour, tag letter, build time, durability, part cost, accuracy (BOOL), fire rate (BOOL), power, weight
		//50, 100, 20
		//DURABILITY - COST - BUILD TIME - POWER - WEIGHT - MATERIAL (for display)
		assaultBoltGold 		= new ItemAssaultBolt(EnumMaterial.GOLD).setUnlocalizedName("assaultBoltGold");
		assaultBoltIron 		= new ItemAssaultBolt(EnumMaterial.IRON).setUnlocalizedName("assaultBoltIron");
		assaultBoltBronze 		= new ItemAssaultBolt(EnumMaterial.BRONZE).setUnlocalizedName("assaultBoltBronze");
		assaultBoltTitanium		= new ItemAssaultBolt(EnumMaterial.TITANIUM).setUnlocalizedName("assaultBoltTitanium");
		assaultBoltAluminium 	= new ItemAssaultBolt(EnumMaterial.ALUMINIUM).setUnlocalizedName("assaultBoltAluminium");
		assaultBoltSteel 		= new ItemAssaultBolt(EnumMaterial.STEEL).setUnlocalizedName("assaultBoltSteel");
		assaultBoltPolymer		= new ItemAssaultBolt(EnumMaterial.POLYMER).setUnlocalizedName("assaultBoltPolymer");
		assaultBoltMythian 		= new ItemAssaultBolt(EnumMaterial.MYTHIAN).setUnlocalizedName("assaultBoltMythian");
		assaultBoltPromethium	= new ItemAssaultBolt(EnumMaterial.PROMETHIUM).setUnlocalizedName("assaultBoltPromethium");
		assaultBoltSarinum 		= new ItemAssaultBolt(EnumMaterial.SARINUM).setUnlocalizedName("assaultBoltSarinum");
		assaultBoltVelerium		= new ItemAssaultBolt(EnumMaterial.VELERIUM).setUnlocalizedName("assaultBoltVelerium");
		assaultBoltCelibras		= new ItemAssaultBolt(EnumMaterial.CELIBRAS).setUnlocalizedName("assaultBoltCelibras");
		assaultBoltAericas 		= new ItemAssaultBolt(EnumMaterial.AERICAS).setUnlocalizedName("assaultBoltAericas");
		assaultBoltDarisin 		= new ItemAssaultBolt(EnumMaterial.DARISIN).setUnlocalizedName("assaultBoltDarisin");
		
		assaultBoltCarrierGold 			= new ItemAssaultBoltCarrier(EnumMaterial.GOLD).setUnlocalizedName("assaultBoltCarrierGold");
		assaultBoltCarrierIron 			= new ItemAssaultBoltCarrier(EnumMaterial.IRON).setUnlocalizedName("assaultBoltCarrierIron");
		assaultBoltCarrierBronze 		= new ItemAssaultBoltCarrier(EnumMaterial.BRONZE).setUnlocalizedName("assaultBoltCarrierBronze");
		assaultBoltCarrierTitanium 		= new ItemAssaultBoltCarrier(EnumMaterial.TITANIUM).setUnlocalizedName("assaultBoltCarrierTitanium");
		assaultBoltCarrierAluminium 	= new ItemAssaultBoltCarrier(EnumMaterial.ALUMINIUM).setUnlocalizedName("assaultBoltCarrierAluminium");
		assaultBoltCarrierSteel 		= new ItemAssaultBoltCarrier(EnumMaterial.STEEL).setUnlocalizedName("assaultBoltCarrierSteel");
		assaultBoltCarrierPolymer 		= new ItemAssaultBoltCarrier(EnumMaterial.POLYMER).setUnlocalizedName("assaultBoltCarrierPolymer");
		assaultBoltCarrierMythian 		= new ItemAssaultBoltCarrier(EnumMaterial.MYTHIAN).setUnlocalizedName("assaultBoltCarrierMythian");
		assaultBoltCarrierPromethium	= new ItemAssaultBoltCarrier(EnumMaterial.PROMETHIUM).setUnlocalizedName("assaultBoltCarrierPromethium");
		assaultBoltCarrierSarinum		= new ItemAssaultBoltCarrier(EnumMaterial.SARINUM).setUnlocalizedName("assaultBoltCarrierSarinum");
		assaultBoltCarrierVelerium 		= new ItemAssaultBoltCarrier(EnumMaterial.VELERIUM).setUnlocalizedName("assaultBoltCarrierVelerium");
		assaultBoltCarrierCelibras 		= new ItemAssaultBoltCarrier(EnumMaterial.CELIBRAS).setUnlocalizedName("assaultBoltCarrierCelibras");
		assaultBoltCarrierAericas 		= new ItemAssaultBoltCarrier(EnumMaterial.AERICAS).setUnlocalizedName("assaultBoltCarrierAericas");
		assaultBoltCarrierDarisin 		= new ItemAssaultBoltCarrier(EnumMaterial.DARISIN).setUnlocalizedName("assaultBoltCarrierDarisin");
		
		assaultChargingHandleGold 		= new ItemAssaultChargingHandle(EnumMaterial.GOLD).setUnlocalizedName("assaultChargingHandleGold");
		assaultChargingHandleIron 		= new ItemAssaultChargingHandle(EnumMaterial.IRON).setUnlocalizedName("assaultChargingHandleIron");
		assaultChargingHandleBronze 	= new ItemAssaultChargingHandle(EnumMaterial.BRONZE).setUnlocalizedName("assaultChargingHandleBronze");
		assaultChargingHandleTitanium 	= new ItemAssaultChargingHandle(EnumMaterial.TITANIUM).setUnlocalizedName("assaultChargingHandleTitanium");
		assaultChargingHandleAluminium 	= new ItemAssaultChargingHandle(EnumMaterial.ALUMINIUM).setUnlocalizedName("assaultChargingHandleAluminium");
		assaultChargingHandleSteel 		= new ItemAssaultChargingHandle(EnumMaterial.STEEL).setUnlocalizedName("assaultChargingHandleSteel");
		assaultChargingHandlePolymer 	= new ItemAssaultChargingHandle(EnumMaterial.POLYMER).setUnlocalizedName("assaultChargingHandlePolymer");
		assaultChargingHandleMythian 	= new ItemAssaultChargingHandle(EnumMaterial.MYTHIAN).setUnlocalizedName("assaultChargingHandleMythian");
		assaultChargingHandlePromethium	= new ItemAssaultChargingHandle(EnumMaterial.PROMETHIUM).setUnlocalizedName("assaultChargingHandlePromethium");
		assaultChargingHandleSarinum	= new ItemAssaultChargingHandle(EnumMaterial.SARINUM).setUnlocalizedName("assaultChargingHandleSarinum");
		assaultChargingHandleVelerium	= new ItemAssaultChargingHandle(EnumMaterial.VELERIUM).setUnlocalizedName("assaultChargingHandleVelerium");
		assaultChargingHandleCelibras 	= new ItemAssaultChargingHandle(EnumMaterial.CELIBRAS).setUnlocalizedName("assaultChargingHandleCelibras");
		assaultChargingHandleAericas 	= new ItemAssaultChargingHandle(EnumMaterial.AERICAS).setUnlocalizedName("assaultChargingHandleAericas");
		assaultChargingHandleDarisin 	= new ItemAssaultChargingHandle(EnumMaterial.DARISIN).setUnlocalizedName("assaultChargingHandleDarisin");
		
		assaultEjectorGold 			= new ItemAssaultEjector(EnumMaterial.GOLD).setUnlocalizedName("assaultEjectorGold");
		assaultEjectorIron 			= new ItemAssaultEjector(EnumMaterial.IRON).setUnlocalizedName("assaultEjectorIron");
		assaultEjectorBronze 		= new ItemAssaultEjector(EnumMaterial.BRONZE).setUnlocalizedName("assaultEjectorBronze");
		assaultEjectorTitanium 		= new ItemAssaultEjector(EnumMaterial.TITANIUM).setUnlocalizedName("assaultEjectorTitanium");
		assaultEjectorAluminium 	= new ItemAssaultEjector(EnumMaterial.ALUMINIUM).setUnlocalizedName("assaultEjectorAluminium");
		assaultEjectorSteel 		= new ItemAssaultEjector(EnumMaterial.STEEL).setUnlocalizedName("assaultEjectorSteel");
		assaultEjectorPolymer 		= new ItemAssaultEjector(EnumMaterial.POLYMER).setUnlocalizedName("assaultEjectorPolymer");
		assaultEjectorMythian 		= new ItemAssaultEjector(EnumMaterial.MYTHIAN).setUnlocalizedName("assaultEjectorMythian");
		assaultEjectorPromethium	= new ItemAssaultEjector(EnumMaterial.PROMETHIUM).setUnlocalizedName("assaultEjectorPromethium");
		assaultEjectorSarinum		= new ItemAssaultEjector(EnumMaterial.SARINUM).setUnlocalizedName("assaultEjectorSarinum");
		assaultEjectorVelerium		= new ItemAssaultEjector(EnumMaterial.VELERIUM).setUnlocalizedName("assaultEjectorVelerium");
		assaultEjectorCelibras 		= new ItemAssaultEjector(EnumMaterial.CELIBRAS).setUnlocalizedName("assaultEjectorCelibras");
		assaultEjectorAericas 		= new ItemAssaultEjector(EnumMaterial.AERICAS).setUnlocalizedName("assaultEjectorAericas");
		assaultEjectorDarisin 		= new ItemAssaultEjector(EnumMaterial.DARISIN).setUnlocalizedName("assaultEjectorDarisin");
		
		assaultExtractorGold 		= new ItemAssaultExtractor(EnumMaterial.GOLD).setUnlocalizedName("assaultExtractorGold");
		assaultExtractorIron 		= new ItemAssaultExtractor(EnumMaterial.IRON).setUnlocalizedName("assaultExtractorIron");
		assaultExtractorBronze 		= new ItemAssaultExtractor(EnumMaterial.BRONZE).setUnlocalizedName("assaultExtractorBronze");
		assaultExtractorTitanium 	= new ItemAssaultExtractor(EnumMaterial.TITANIUM).setUnlocalizedName("assaultExtractorTitanium");
		assaultExtractorAluminium 	= new ItemAssaultExtractor(EnumMaterial.ALUMINIUM).setUnlocalizedName("assaultExtractorAluminium");
		assaultExtractorSteel 		= new ItemAssaultExtractor(EnumMaterial.STEEL).setUnlocalizedName("assaultExtractorSteel");
		assaultExtractorPolymer 	= new ItemAssaultExtractor(EnumMaterial.POLYMER).setUnlocalizedName("assaultExtractorPolymer");
		assaultExtractorMythian 	= new ItemAssaultExtractor(EnumMaterial.MYTHIAN).setUnlocalizedName("assaultExtractorMythian");
		assaultExtractorPromethium	= new ItemAssaultExtractor(EnumMaterial.PROMETHIUM).setUnlocalizedName("assaultExtractorPromethium");
		assaultExtractorSarinum 	= new ItemAssaultExtractor(EnumMaterial.SARINUM).setUnlocalizedName("assaultExtractorSarinum");
		assaultExtractorVelerium	= new ItemAssaultExtractor(EnumMaterial.VELERIUM).setUnlocalizedName("assaultExtractorVelerium");
		assaultExtractorCelibras 	= new ItemAssaultExtractor(EnumMaterial.CELIBRAS).setUnlocalizedName("assaultExtractorCelibras");
		assaultExtractorAericas 	= new ItemAssaultExtractor(EnumMaterial.AERICAS).setUnlocalizedName("assaultExtractorAericas");
		assaultExtractorDarisin 	= new ItemAssaultExtractor(EnumMaterial.DARISIN).setUnlocalizedName("assaultExtractorDarisin");
		
		assaultFiringPinGold 		= new ItemAssaultFiringPin(EnumMaterial.GOLD).setUnlocalizedName("assaultFiringPinGold");
		assaultFiringPinIron 		= new ItemAssaultFiringPin(EnumMaterial.IRON).setUnlocalizedName("assaultFiringPinIron");
		assaultFiringPinBronze 		= new ItemAssaultFiringPin(EnumMaterial.BRONZE).setUnlocalizedName("assaultFiringPinBronze");
		assaultFiringPinTitanium 	= new ItemAssaultFiringPin(EnumMaterial.TITANIUM).setUnlocalizedName("assaultFiringPinTitanium");
		assaultFiringPinAluminium 	= new ItemAssaultFiringPin(EnumMaterial.ALUMINIUM).setUnlocalizedName("assaultFiringPinAluminium");
		assaultFiringPinSteel 		= new ItemAssaultFiringPin(EnumMaterial.STEEL).setUnlocalizedName("assaultFiringPinSteel");
		assaultFiringPinPolymer 	= new ItemAssaultFiringPin(EnumMaterial.POLYMER).setUnlocalizedName("assaultFiringPinPolymer");
		assaultFiringPinMythian 	= new ItemAssaultFiringPin(EnumMaterial.MYTHIAN).setUnlocalizedName("assaultFiringPinMythian");
		assaultFiringPinPromethium	= new ItemAssaultFiringPin(EnumMaterial.PROMETHIUM).setUnlocalizedName("assaultFiringPinPromethium");
		assaultFiringPinSarinum		= new ItemAssaultFiringPin(EnumMaterial.SARINUM).setUnlocalizedName("assaultFiringPinSarinum");
		assaultFiringPinVelerium	= new ItemAssaultFiringPin(EnumMaterial.VELERIUM).setUnlocalizedName("assaultFiringPinVelerium");
		assaultFiringPinCelibras 	= new ItemAssaultFiringPin(EnumMaterial.CELIBRAS).setUnlocalizedName("assaultFiringPinCelibras");
		assaultFiringPinAericas 	= new ItemAssaultFiringPin(EnumMaterial.AERICAS).setUnlocalizedName("assaultFiringPinAericas");
		assaultFiringPinDarisin 	= new ItemAssaultFiringPin(EnumMaterial.DARISIN).setUnlocalizedName("assaultFiringPinDarisin");
		
		assaultFiringPinRetainerPinGold 		= new ItemAssaultFiringPinRetainerPin(EnumMaterial.GOLD).setUnlocalizedName("assaultFiringPinRetainerPinGold");
		assaultFiringPinRetainerPinIron 		= new ItemAssaultFiringPinRetainerPin(EnumMaterial.IRON).setUnlocalizedName("assaultFiringPinRetainerPinIron");
		assaultFiringPinRetainerPinBronze 		= new ItemAssaultFiringPinRetainerPin(EnumMaterial.BRONZE).setUnlocalizedName("assaultFiringPinRetainerPinBronze");
		assaultFiringPinRetainerPinTitanium 	= new ItemAssaultFiringPinRetainerPin(EnumMaterial.TITANIUM).setUnlocalizedName("assaultFiringPinRetainerPinTitanium");
		assaultFiringPinRetainerPinAluminium 	= new ItemAssaultFiringPinRetainerPin(EnumMaterial.ALUMINIUM).setUnlocalizedName("assaultFiringPinRetainerPinAluminium");
		assaultFiringPinRetainerPinSteel 		= new ItemAssaultFiringPinRetainerPin(EnumMaterial.STEEL).setUnlocalizedName("assaultFiringPinRetainerPinSteel");
		assaultFiringPinRetainerPinPolymer 		= new ItemAssaultFiringPinRetainerPin(EnumMaterial.POLYMER).setUnlocalizedName("assaultFiringPinRetainerPinPolymer");
		assaultFiringPinRetainerPinMythian 		= new ItemAssaultFiringPinRetainerPin(EnumMaterial.MYTHIAN).setUnlocalizedName("assaultFiringPinRetainerPinMythian");
		assaultFiringPinRetainerPinPromethium	= new ItemAssaultFiringPinRetainerPin(EnumMaterial.PROMETHIUM).setUnlocalizedName("assaultFiringPinRetainerPinPromethium");
		assaultFiringPinRetainerPinSarinum 		= new ItemAssaultFiringPinRetainerPin(EnumMaterial.SARINUM).setUnlocalizedName("assaultFiringPinRetainerPinSarinum");
		assaultFiringPinRetainerPinVelerium		= new ItemAssaultFiringPinRetainerPin(EnumMaterial.VELERIUM).setUnlocalizedName("assaultFiringPinRetainerPinVelerium");
		assaultFiringPinRetainerPinCelibras 	= new ItemAssaultFiringPinRetainerPin(EnumMaterial.CELIBRAS).setUnlocalizedName("assaultFiringPinRetainerPinCelibras");
		assaultFiringPinRetainerPinAericas 		= new ItemAssaultFiringPinRetainerPin(EnumMaterial.AERICAS).setUnlocalizedName("assaultFiringPinRetainerPinAericas");
		assaultFiringPinRetainerPinDarisin 		= new ItemAssaultFiringPinRetainerPin(EnumMaterial.DARISIN).setUnlocalizedName("assaultFiringPinRetainerPinDarisin");

		//DURABILITY - COST - BUILD TIME - POWER - WEIGHT - FIRE RATE - MATERIAL (for display)
		assaultPistonChamberGold		= new ItemAssaultPistonChamber(EnumMaterial.GOLD).setUnlocalizedName("assaultPistonChamberGold");
		assaultPistonChamberIron 		= new ItemAssaultPistonChamber(EnumMaterial.IRON).setUnlocalizedName("assaultPistonChamberIron");
		assaultPistonChamberBronze 		= new ItemAssaultPistonChamber(EnumMaterial.BRONZE).setUnlocalizedName("assaultPistonChamberBronze");
		assaultPistonChamberTitanium 	= new ItemAssaultPistonChamber(EnumMaterial.TITANIUM).setUnlocalizedName("assaultPistonChamberTitanium");
		assaultPistonChamberAluminium 	= new ItemAssaultPistonChamber(EnumMaterial.ALUMINIUM).setUnlocalizedName("assaultPistonChamberAluminium");
		assaultPistonChamberSteel 		= new ItemAssaultPistonChamber(EnumMaterial.STEEL).setUnlocalizedName("assaultPistonChamberSteel");
		assaultPistonChamberPolymer 	= new ItemAssaultPistonChamber(EnumMaterial.POLYMER).setUnlocalizedName("assaultPistonChamberPolymer");
		assaultPistonChamberMythian 	= new ItemAssaultPistonChamber(EnumMaterial.MYTHIAN).setUnlocalizedName("assaultPistonChamberMythian");
		assaultPistonChamberPromethium 	= new ItemAssaultPistonChamber(EnumMaterial.PROMETHIUM).setUnlocalizedName("assaultPistonChamberPromethium");
		assaultPistonChamberSarinum		= new ItemAssaultPistonChamber(EnumMaterial.SARINUM).setUnlocalizedName("assaultPistonChamberSarinum");
		assaultPistonChamberVelerium	= new ItemAssaultPistonChamber(EnumMaterial.VELERIUM).setUnlocalizedName("assaultPistonChamberVelerium");
		assaultPistonChamberCelibras 	= new ItemAssaultPistonChamber(EnumMaterial.CELIBRAS).setUnlocalizedName("assaultPistonChamberCelibras");
		assaultPistonChamberAericas 	= new ItemAssaultPistonChamber(EnumMaterial.AERICAS).setUnlocalizedName("assaultPistonChamberAericas");
		assaultPistonChamberDarisin 	= new ItemAssaultPistonChamber(EnumMaterial.DARISIN).setUnlocalizedName("assaultPistonChamberDarisin");
		
		assaultSpringGold 		= new ItemAssaultSpring(EnumMaterial.GOLD).setUnlocalizedName("assaultSpringGold");
		assaultSpringIron 		= new ItemAssaultSpring(EnumMaterial.IRON).setUnlocalizedName("assaultSpringIron");
		assaultSpringBronze 	= new ItemAssaultSpring(EnumMaterial.BRONZE).setUnlocalizedName("assaultSpringBronze");
		assaultSpringTitanium 	= new ItemAssaultSpring(EnumMaterial.TITANIUM).setUnlocalizedName("assaultSpringTitanium");
		assaultSpringAluminium 	= new ItemAssaultSpring(EnumMaterial.ALUMINIUM).setUnlocalizedName("assaultSpringAluminium");
		assaultSpringSteel 		= new ItemAssaultSpring(EnumMaterial.STEEL).setUnlocalizedName("assaultSpringSteel");
		assaultSpringPolymer 	= new ItemAssaultSpring(EnumMaterial.POLYMER).setUnlocalizedName("assaultSpringPolymer");
		assaultSpringMythian 	= new ItemAssaultSpring(EnumMaterial.MYTHIAN).setUnlocalizedName("assaultSpringMythian");
		assaultSpringPromethium = new ItemAssaultSpring(EnumMaterial.PROMETHIUM).setUnlocalizedName("assaultSpringPromethium");
		assaultSpringSarinum	= new ItemAssaultSpring(EnumMaterial.SARINUM).setUnlocalizedName("assaultSpringSarinum");
		assaultSpringVelerium	= new ItemAssaultSpring(EnumMaterial.VELERIUM).setUnlocalizedName("assaultSpringVelerium");
		assaultSpringCelibras 	= new ItemAssaultSpring(EnumMaterial.CELIBRAS).setUnlocalizedName("assaultSpringCelibras");
		assaultSpringAericas 	= new ItemAssaultSpring(EnumMaterial.AERICAS).setUnlocalizedName("assaultSpringAericas");
		assaultSpringDarisin 	= new ItemAssaultSpring(EnumMaterial.DARISIN).setUnlocalizedName("assaultSpringDarisin");
		
		assaultPistonGold 		= new ItemAssaultPiston(EnumMaterial.GOLD).setUnlocalizedName("assaultPistonGold");
		assaultPistonIron 		= new ItemAssaultPiston(EnumMaterial.IRON).setUnlocalizedName("assaultPistonIron");
		assaultPistonBronze 	= new ItemAssaultPiston(EnumMaterial.BRONZE).setUnlocalizedName("assaultPistonBronze");
		assaultPistonTitanium 	= new ItemAssaultPiston(EnumMaterial.TITANIUM).setUnlocalizedName("assaultPistonTitanium");
		assaultPistonAluminium 	= new ItemAssaultPiston(EnumMaterial.ALUMINIUM).setUnlocalizedName("assaultPistonAluminium");
		assaultPistonSteel 		= new ItemAssaultPiston(EnumMaterial.STEEL).setUnlocalizedName("assaultPistonSteel");
		assaultPistonPolymer 	= new ItemAssaultPiston(EnumMaterial.POLYMER).setUnlocalizedName("assaultPistonPolymer");
		assaultPistonMythian 	= new ItemAssaultPiston(EnumMaterial.MYTHIAN).setUnlocalizedName("assaultPistonMythian");
		assaultPistonPromethium = new ItemAssaultPiston(EnumMaterial.PROMETHIUM).setUnlocalizedName("assaultPistonPromethium");
		assaultPistonSarinum	= new ItemAssaultPiston(EnumMaterial.SARINUM).setUnlocalizedName("assaultPistonSarinum");
		assaultPistonVelerium	= new ItemAssaultPiston(EnumMaterial.VELERIUM).setUnlocalizedName("assaultPistonVelerium");
		assaultPistonCelibras 	= new ItemAssaultPiston(EnumMaterial.CELIBRAS).setUnlocalizedName("assaultPistonCelibras");
		assaultPistonAericas 	= new ItemAssaultPiston(EnumMaterial.AERICAS).setUnlocalizedName("assaultPistonAericas");
		assaultPistonDarisin 	= new ItemAssaultPiston(EnumMaterial.DARISIN).setUnlocalizedName("assaultPistonDarisin");
		
		assaultGasChamberGold 		= new ItemAssaultGasChamber(EnumMaterial.GOLD).setUnlocalizedName("assaultGasChamberGold");
		assaultGasChamberIron 		= new ItemAssaultGasChamber(EnumMaterial.IRON).setUnlocalizedName("assaultGasChamberIron");
		assaultGasChamberBronze 	= new ItemAssaultGasChamber(EnumMaterial.BRONZE).setUnlocalizedName("assaultGasChamberBronze");
		assaultGasChamberTitanium 	= new ItemAssaultGasChamber(EnumMaterial.TITANIUM).setUnlocalizedName("assaultGasChamberTitanium");
		assaultGasChamberAluminium 	= new ItemAssaultGasChamber(EnumMaterial.ALUMINIUM).setUnlocalizedName("assaultGasChamberAluminium");
		assaultGasChamberSteel 		= new ItemAssaultGasChamber(EnumMaterial.STEEL).setUnlocalizedName("assaultGasChamberSteel");
		assaultGasChamberPolymer 	= new ItemAssaultGasChamber(EnumMaterial.POLYMER).setUnlocalizedName("assaultGasChamberPolymer");
		assaultGasChamberMythian 	= new ItemAssaultGasChamber(EnumMaterial.MYTHIAN).setUnlocalizedName("assaultGasChamberMythian");
		assaultGasChamberPromethium = new ItemAssaultGasChamber(EnumMaterial.PROMETHIUM).setUnlocalizedName("assaultGasChamberPromethium");
		assaultGasChamberSarinum 	= new ItemAssaultGasChamber(EnumMaterial.SARINUM).setUnlocalizedName("assaultGasChamberSarinum");
		assaultGasChamberVelerium	= new ItemAssaultGasChamber(EnumMaterial.VELERIUM).setUnlocalizedName("assaultGasChamberVelerium");
		assaultGasChamberCelibras 	= new ItemAssaultGasChamber(EnumMaterial.CELIBRAS).setUnlocalizedName("assaultGasChamberCelibras");
		assaultGasChamberAericas 	= new ItemAssaultGasChamber(EnumMaterial.AERICAS).setUnlocalizedName("assaultGasChamberAericas");
		assaultGasChamberDarisin 	= new ItemAssaultGasChamber(EnumMaterial.DARISIN).setUnlocalizedName("assaultGasChamberDarisin");
		
		assaultGasFeedGold 			= new ItemAssaultGasFeed(EnumMaterial.GOLD).setUnlocalizedName("assaultGasFeedGold");
		assaultGasFeedIron 			= new ItemAssaultGasFeed(EnumMaterial.IRON).setUnlocalizedName("assaultGasFeedIron");
		assaultGasFeedBronze 		= new ItemAssaultGasFeed(EnumMaterial.BRONZE).setUnlocalizedName("assaultGasFeedBronze");
		assaultGasFeedTitanium 		= new ItemAssaultGasFeed(EnumMaterial.TITANIUM).setUnlocalizedName("assaultGasFeedTitanium");
		assaultGasFeedAluminium 	= new ItemAssaultGasFeed(EnumMaterial.ALUMINIUM).setUnlocalizedName("assaultGasFeedAluminium");
		assaultGasFeedSteel 		= new ItemAssaultGasFeed(EnumMaterial.STEEL).setUnlocalizedName("assaultGasFeedSteel");
		assaultGasFeedPolymer 		= new ItemAssaultGasFeed(EnumMaterial.POLYMER).setUnlocalizedName("assaultGasFeedPolymer");
		assaultGasFeedMythian 		= new ItemAssaultGasFeed(EnumMaterial.MYTHIAN).setUnlocalizedName("assaultGasFeedMythian");
		assaultGasFeedPromethium 	= new ItemAssaultGasFeed(EnumMaterial.PROMETHIUM).setUnlocalizedName("assaultGasFeedPromethium");
		assaultGasFeedSarinum 		= new ItemAssaultGasFeed(EnumMaterial.SARINUM).setUnlocalizedName("assaultGasFeedSarinum");
		assaultGasFeedVelerium		= new ItemAssaultGasFeed(EnumMaterial.VELERIUM).setUnlocalizedName("assaultGasFeedVelerium");
		assaultGasFeedCelibras 		= new ItemAssaultGasFeed(EnumMaterial.CELIBRAS).setUnlocalizedName("assaultGasFeedCelibras");
		assaultGasFeedAericas 		= new ItemAssaultGasFeed(EnumMaterial.AERICAS).setUnlocalizedName("assaultGasFeedAericas");
		assaultGasFeedDarisin 		= new ItemAssaultGasFeed(EnumMaterial.DARISIN).setUnlocalizedName("assaultGasFeedDarisin");

		
		//DURABILITY - COST - BUILD TIME - POWER - WEIGHT - MATERIAL (for display) - CALIBRE (mm - NATO)
		assaultChamberGold 			= new ItemAssaultChamber(EnumMaterial.GOLD).setUnlocalizedName("assaultChamberGold");
		assaultChamberIron 			= new ItemAssaultChamber(EnumMaterial.IRON).setUnlocalizedName("assaultChamberIron");
		assaultChamberBronze 		= new ItemAssaultChamber(EnumMaterial.BRONZE).setUnlocalizedName("assaultChamberBronze");
		assaultChamberTitanium 		= new ItemAssaultChamber(EnumMaterial.TITANIUM).setUnlocalizedName("assaultChamberTitanium");
		assaultChamberAluminium 	= new ItemAssaultChamber(EnumMaterial.ALUMINIUM).setUnlocalizedName("assaultChamberAluminium");
		assaultChamberSteel 		= new ItemAssaultChamber(EnumMaterial.STEEL).setUnlocalizedName("assaultChamberSteel");
		assaultChamberPolymer 		= new ItemAssaultChamber(EnumMaterial.POLYMER).setUnlocalizedName("assaultChamberPolymer");
		assaultChamberMythian 		= new ItemAssaultChamber(EnumMaterial.MYTHIAN).setUnlocalizedName("assaultChamberMythian");
		assaultChamberPromethium	= new ItemAssaultChamber(EnumMaterial.PROMETHIUM).setUnlocalizedName("assaultChamberPromethium");
		assaultChamberSarinum 		= new ItemAssaultChamber(EnumMaterial.SARINUM).setUnlocalizedName("assaultChamberSarinum");
		assaultChamberVelerium 		= new ItemAssaultChamber(EnumMaterial.VELERIUM).setUnlocalizedName("assaultChamberVelerium");
		assaultChamberCelibras		= new ItemAssaultChamber(EnumMaterial.CELIBRAS).setUnlocalizedName("assaultChamberCelibras");
		assaultChamberAericas 		= new ItemAssaultChamber(EnumMaterial.AERICAS).setUnlocalizedName("assaultChamberAericas");
		assaultChamberDarisin 		= new ItemAssaultChamber(EnumMaterial.DARISIN).setUnlocalizedName("assaultChamberDarisin");
		
		assaultReceiverM4Gold = new M4Receiver("Gold M4A1 Receiver", "m4receiverGold", "assault", EnumMaterial.GOLD, true).setUnlocalizedName("assaultReceiverM4Gold");
		assaultReceiverM4Iron = new M4Receiver("Iron M4A1 Receiver", "m4receiverIron", "assault", EnumMaterial.IRON, true).setUnlocalizedName("assaultReceiverM4Iron");
		assaultReceiverM4Bronze = new M4Receiver("Bronze M4A1 Receiver", "m4receiverBronze", "assault", EnumMaterial.BRONZE, true).setUnlocalizedName("assaultReceiverM4Bronze");
		assaultReceiverM4Titanium = new M4Receiver("Titanium M4A1 Receiver", "m4receiverTitanium", "assault", EnumMaterial.TITANIUM, true).setUnlocalizedName("assaultReceiverM4Titanium");
		assaultReceiverM4Aluminium = new M4Receiver("Aluminium M4A1 Receiver", "m4receiverAluminium", "assault", EnumMaterial.ALUMINIUM, true).setUnlocalizedName("assaultReceiverM4Aluminium");
		assaultReceiverM4Steel = new M4Receiver("Steel M4A1 Receiver", "m4receiverSteel", "assault", EnumMaterial.STEEL, true).setUnlocalizedName("assaultReceiverM4Steel");
		assaultReceiverM4Polymer = new M4Receiver("Polymer M4A1 Receiver", "m4receiverPolymer", "assault", EnumMaterial.POLYMER, true).setUnlocalizedName("assaultReceiverM4Polymer");
		assaultReceiverM4Mythian = new M4Receiver("Mythian M4A1 Receiver", "m4receiverMythian", "assault", EnumMaterial.MYTHIAN, true).setUnlocalizedName("assaultReceiverM4Mythian");
		assaultReceiverM4Promethium = new M4Receiver("Promethium M4A1 Receiver", "m4receiverPromethium", "assault", EnumMaterial.PROMETHIUM, true).setUnlocalizedName("assaultReceiverM4Promethium");
		assaultReceiverM4Sarinum = new M4Receiver("Sarinum M4A1 Receiver", "m4receiverSarinum", "assault", EnumMaterial.SARINUM, true).setUnlocalizedName("assaultReceiverM4Sarinum");
		assaultReceiverM4Velerium = new M4Receiver("Velerium M4A1 Receiver", "m4receiverVelerium", "assault", EnumMaterial.VELERIUM, true).setUnlocalizedName("assaultReceiverM4Velerium");
		assaultReceiverM4Celibras = new M4Receiver("Celibras M4A1 Receiver", "m4receiverCelibras", "assault", EnumMaterial.CELIBRAS, true).setUnlocalizedName("assaultReceiverM4Celibras");
		assaultReceiverM4Aericas = new M4Receiver("Aericas M4A1 Receiver", "m4receiverAericas", "assault", EnumMaterial.AERICAS, true).setUnlocalizedName("assaultReceiverM4Aericas");
		assaultReceiverM4Darisin = new M4Receiver("Darisin M4A1 Receiver", "m4receiverDarisin", "assault", EnumMaterial.DARISIN, true).setUnlocalizedName("assaultReceiverM4Darisin");
		
		assaultFrontEndM4Gold = new M4FrontEnd("Gold M4A1 Front End", "m4frontEndGold", "assault", EnumMaterial.GOLD, true, true, true, true).setUnlocalizedName("assaultFrontEndM4Gold");
		assaultFrontEndM4Iron = new M4FrontEnd("Iron M4A1 Front End", "m4frontEndIron", "assault", EnumMaterial.IRON, true, true, true, true).setUnlocalizedName("assaultFrontEndM4Iron");
		assaultFrontEndM4Bronze = new M4FrontEnd("Bronze M4A1 Front End", "m4frontEndBronze", "assault", EnumMaterial.BRONZE, true, true, true, true).setUnlocalizedName("assaultFrontEndM4Bronze");
		assaultFrontEndM4Titanium = new M4FrontEnd("Titanium M4A1 Front End", "m4frontEndTitanium", "assault", EnumMaterial.TITANIUM, true, true, true, true).setUnlocalizedName("assaultFrontEndM4Titanium");
		assaultFrontEndM4Aluminium = new M4FrontEnd("Aluminium M4A1 Front End", "m4frontEndAluminium", "assault", EnumMaterial.ALUMINIUM, true, true, true, true).setUnlocalizedName("assaultFrontEndM4Aluminium");
		assaultFrontEndM4Steel = new M4FrontEnd("Steel M4A1 Front End", "m4frontEndSteel", "assault", EnumMaterial.STEEL, true, true, true, true).setUnlocalizedName("assaultFrontEndM4Steel");
		assaultFrontEndM4Polymer = new M4FrontEnd("Polymer M4A1 Front End", "m4frontEndPolymer", "assault", EnumMaterial.POLYMER, true, true, true, true).setUnlocalizedName("assaultFrontEndM4Polymer");
		assaultFrontEndM4Mythian = new M4FrontEnd("Mythian M4A1 Front End", "m4frontEndMythian", "assault", EnumMaterial.MYTHIAN, true, true, true, true).setUnlocalizedName("assaultFrontEndM4Mythian");
		assaultFrontEndM4Promethium = new M4FrontEnd("Promethium M4A1 Front End", "m4frontEndPromethium", "assault", EnumMaterial.PROMETHIUM, true, true, true, true).setUnlocalizedName("assaultFrontEndM4Promethium");
		assaultFrontEndM4Sarinum = new M4FrontEnd("Sarinum M4A1 Front End", "m4frontEndSarinum", "assault", EnumMaterial.SARINUM, true, true, true, true).setUnlocalizedName("assaultFrontEndM4Sarinum");
		assaultFrontEndM4Velerium = new M4FrontEnd("Velerium M4A1 Front End", "m4frontEndVelerium", "assault", EnumMaterial.VELERIUM, true, true, true, true).setUnlocalizedName("assaultFrontEndM4Velerium");
		assaultFrontEndM4Celibras = new M4FrontEnd("Celibras M4A1 Front End", "m4frontEndCelibras", "assault", EnumMaterial.CELIBRAS, true, true, true, true).setUnlocalizedName("assaultFrontEndM4Celibras");
		assaultFrontEndM4Aericas = new M4FrontEnd("Aericas M4A1 Front End", "m4frontEndAericas", "assault", EnumMaterial.AERICAS, true, true, true, true).setUnlocalizedName("assaultFrontEndM4Aericas");
		assaultFrontEndM4Darisin = new M4FrontEnd("Darisin M4A1 Front End", "m4frontEndDarisin", "assault", EnumMaterial.DARISIN, true, true, true, true).setUnlocalizedName("assaultFrontEndM4Darisin");
		
		assaultStockM4Gold = new M4Stock("Gold M4A1 Stock", "m4stockGold", "assault", EnumMaterial.GOLD).setUnlocalizedName("assaultStockM4Gold");
		assaultStockM4Iron = new M4Stock("Iron M4A1 Stock", "m4stockIron", "assault", EnumMaterial.IRON).setUnlocalizedName("assaultStockM4Iron");
		assaultStockM4Bronze = new M4Stock("Bronze M4A1 Stock", "m4stockBronze", "assault", EnumMaterial.BRONZE).setUnlocalizedName("assaultStockM4Bronze");
		assaultStockM4Titanium = new M4Stock("Titanium M4A1 Stock", "m4stockTitanium", "assault", EnumMaterial.TITANIUM).setUnlocalizedName("assaultStockM4Titanium");
		assaultStockM4Aluminium = new M4Stock("Aluminium M4A1 Stock", "m4stockAluminium", "assault", EnumMaterial.ALUMINIUM).setUnlocalizedName("assaultStockM4Aluminium");
		assaultStockM4Steel = new M4Stock("Steel M4A1 Stock", "m4stockSteel", "assault", EnumMaterial.STEEL).setUnlocalizedName("assaultStockM4Steel");
		assaultStockM4Polymer = new M4Stock("Polymer M4A1 Stock", "m4stockPolymer", "assault", EnumMaterial.POLYMER).setUnlocalizedName("assaultStockM4Polymer");
		assaultStockM4Mythian = new M4Stock("Mythian M4A1 Stock", "m4stockMythian", "assault", EnumMaterial.MYTHIAN).setUnlocalizedName("assaultStockM4Mythian");
		assaultStockM4Promethium = new M4Stock("Promethium M4A1 Stock", "m4stockPromethium", "assault", EnumMaterial.PROMETHIUM).setUnlocalizedName("assaultStockM4Promethium");
		assaultStockM4Sarinum = new M4Stock("Sarinum M4A1 Stock", "m4stockSarinum", "assault", EnumMaterial.SARINUM).setUnlocalizedName("assaultStockM4Sarinum");
		assaultStockM4Velerium = new M4Stock("Velerium M4A1 Stock", "m4stockVelerium", "assault", EnumMaterial.VELERIUM).setUnlocalizedName("assaultStockM4Velerium");
		assaultStockM4Celibras = new M4Stock("Celibras M4A1 Stock", "m4stockCelibras", "assault", EnumMaterial.CELIBRAS).setUnlocalizedName("assaultStockM4Celibras");
		assaultStockM4Aericas = new M4Stock("Aericas M4A1 Stock", "m4stockAericas", "assault", EnumMaterial.AERICAS).setUnlocalizedName("assaultStockM4Aericas");
		assaultStockM4Darisin = new M4Stock("Darisin M4A1 Stock", "m4stockDarisin", "assault", EnumMaterial.DARISIN).setUnlocalizedName("assaultStockM4Darisin");
	}
	
	public static void registerItems() {
		GameRegistry.registerItem(assaultBoltGold, "assaultBoltGold");
		GameRegistry.registerItem(assaultBoltIron, "assaultBoltIron");
		GameRegistry.registerItem(assaultBoltBronze, "assaultBoltBronze");
		GameRegistry.registerItem(assaultBoltTitanium, "assaultBoltTitanium");
		GameRegistry.registerItem(assaultBoltAluminium, "assaultBoltAluminium");
		GameRegistry.registerItem(assaultBoltSteel, "assaultBoltSteel");
		GameRegistry.registerItem(assaultBoltPolymer, "assaultBoltPolymer");
		GameRegistry.registerItem(assaultBoltMythian, "assaultBoltMythian");
		GameRegistry.registerItem(assaultBoltPromethium, "assaultBoltPromethium");
		GameRegistry.registerItem(assaultBoltSarinum, "assaultBoltSarinum");
		GameRegistry.registerItem(assaultBoltVelerium, "assaultBoltVeleriumn");
		GameRegistry.registerItem(assaultBoltCelibras, "assaultBoltCelibras");
		GameRegistry.registerItem(assaultBoltAericas, "assaultBoltAericas");
		GameRegistry.registerItem(assaultBoltDarisin, "assaultBoltDarisin");
		
		GameRegistry.registerItem(assaultBoltCarrierGold, "assaultBoltCarrierGold");
		GameRegistry.registerItem(assaultBoltCarrierIron, "assaultBoltCarrierIron");
		GameRegistry.registerItem(assaultBoltCarrierBronze, "assaultBoltCarrierBronze");
		GameRegistry.registerItem(assaultBoltCarrierTitanium, "assaultBoltCarrierTitanium");
		GameRegistry.registerItem(assaultBoltCarrierAluminium, "assaultBoltCarrierAluminium");
		GameRegistry.registerItem(assaultBoltCarrierSteel, "assaultBoltCarrierSteel");
		GameRegistry.registerItem(assaultBoltCarrierPolymer, "assaultBoltCarrierPolymer");
		GameRegistry.registerItem(assaultBoltCarrierMythian, "assaultBoltCarrierMythian");
		GameRegistry.registerItem(assaultBoltCarrierPromethium, "assaultBoltCarrierPromethium");
		GameRegistry.registerItem(assaultBoltCarrierSarinum, "assaultBoltCarrierSarinum");
		GameRegistry.registerItem(assaultBoltCarrierVelerium, "assaultBoltCarrierVelerium");
		GameRegistry.registerItem(assaultBoltCarrierCelibras, "assaultBoltCarrierCelibras");
		GameRegistry.registerItem(assaultBoltCarrierAericas, "assaultBoltCarrierAericas");
		GameRegistry.registerItem(assaultBoltCarrierDarisin, "assaultBoltCarrierDarisin");
		
		GameRegistry.registerItem(assaultChargingHandleGold, "assaultChargingHandleGold");
		GameRegistry.registerItem(assaultChargingHandleIron, "assaultChargingHandleIron");
		GameRegistry.registerItem(assaultChargingHandleBronze, "assaultChargingHandleBronze");
		GameRegistry.registerItem(assaultChargingHandleTitanium, "assaultChargingHandleTitanium");
		GameRegistry.registerItem(assaultChargingHandleAluminium, "assaultChargingHandleAluminium");
		GameRegistry.registerItem(assaultChargingHandleSteel, "assaultChargingHandleSteel");
		GameRegistry.registerItem(assaultChargingHandlePolymer, "assaultChargingHandlePolymer");
		GameRegistry.registerItem(assaultChargingHandleMythian, "assaultChargingHandleMythian");
		GameRegistry.registerItem(assaultChargingHandlePromethium, "assaultChargingHandlePromethium");
		GameRegistry.registerItem(assaultChargingHandleSarinum, "assaultChargingHandleSarinum");
		GameRegistry.registerItem(assaultChargingHandleVelerium, "assaultChargingHandleVelerium");
		GameRegistry.registerItem(assaultChargingHandleCelibras, "assaultChargingHandleCelibras");
		GameRegistry.registerItem(assaultChargingHandleAericas, "assaultChargingHandleAericas");
		GameRegistry.registerItem(assaultChargingHandleDarisin, "assaultChargingHandleDarisin");
		
		GameRegistry.registerItem(assaultEjectorGold, "assaultEjectorGold");
		GameRegistry.registerItem(assaultEjectorIron, "assaultEjectorIron");
		GameRegistry.registerItem(assaultEjectorBronze, "assaultEjectorBronze");
		GameRegistry.registerItem(assaultEjectorTitanium, "assaultEjectorTitanium");
		GameRegistry.registerItem(assaultEjectorAluminium, "assaultEjectorAluminium");
		GameRegistry.registerItem(assaultEjectorSteel, "assaultEjectorSteel");
		GameRegistry.registerItem(assaultEjectorPolymer, "assaultEjectorPolymer");
		GameRegistry.registerItem(assaultEjectorMythian, "assaultEjectorMythian");
		GameRegistry.registerItem(assaultEjectorPromethium, "assaultEjectorPromethium");
		GameRegistry.registerItem(assaultEjectorSarinum, "assaultEjectorSarinum");
		GameRegistry.registerItem(assaultEjectorVelerium, "assaultEjectorVelerium");
		GameRegistry.registerItem(assaultEjectorCelibras, "assaultEjectorCelibras");
		GameRegistry.registerItem(assaultEjectorAericas, "assaultEjectorAericas");
		GameRegistry.registerItem(assaultEjectorDarisin, "assaultEjectorDarisin");
		
		GameRegistry.registerItem(assaultExtractorGold, "assaultExtractorGold");
		GameRegistry.registerItem(assaultExtractorIron, "assaultExtractorIron");
		GameRegistry.registerItem(assaultExtractorBronze, "assaultExtractorBronze");
		GameRegistry.registerItem(assaultExtractorTitanium, "assaultExtractorTitanium");
		GameRegistry.registerItem(assaultExtractorAluminium, "assaultExtractorAluminium");
		GameRegistry.registerItem(assaultExtractorSteel, "assaultExtractorSteel");
		GameRegistry.registerItem(assaultExtractorPolymer, "assaultExtractorPolymer");
		GameRegistry.registerItem(assaultExtractorMythian, "assaultExtractorMythian");
		GameRegistry.registerItem(assaultExtractorPromethium, "assaultExtractorPromethium");
		GameRegistry.registerItem(assaultExtractorSarinum, "assaultExtractorSarinum");
		GameRegistry.registerItem(assaultExtractorVelerium, "assaultExtractorVelerium");
		GameRegistry.registerItem(assaultExtractorCelibras, "assaultExtractorCelibras");
		GameRegistry.registerItem(assaultExtractorAericas, "assaultExtractorAericas");
		GameRegistry.registerItem(assaultExtractorDarisin, "assaultExtractorDarisin");
		
		GameRegistry.registerItem(assaultFiringPinGold, "assaultFiringPinGold");
		GameRegistry.registerItem(assaultFiringPinIron, "assaultFiringPinIron");
		GameRegistry.registerItem(assaultFiringPinBronze, "assaultFiringPinBronze");
		GameRegistry.registerItem(assaultFiringPinTitanium, "assaultFiringPinTitanium");
		GameRegistry.registerItem(assaultFiringPinAluminium, "assaultFiringPinAluminium");
		GameRegistry.registerItem(assaultFiringPinSteel, "assaultFiringPinSteel");
		GameRegistry.registerItem(assaultFiringPinPolymer, "assaultFiringPinPolymer");
		GameRegistry.registerItem(assaultFiringPinMythian, "assaultFiringPinMythian");
		GameRegistry.registerItem(assaultFiringPinPromethium, "assaultFiringPinPromethium");
		GameRegistry.registerItem(assaultFiringPinSarinum, "assaultFiringPinSarinum");
		GameRegistry.registerItem(assaultFiringPinVelerium, "assaultFiringPinVelerium");
		GameRegistry.registerItem(assaultFiringPinCelibras, "assaultFiringPinCelibras");
		GameRegistry.registerItem(assaultFiringPinAericas, "assaultFiringPinAericas");
		GameRegistry.registerItem(assaultFiringPinDarisin, "assaultFiringPinDarisin");
		
		GameRegistry.registerItem(assaultFiringPinRetainerPinGold, "assaultFiringPinRetainerPinGold");
		GameRegistry.registerItem(assaultFiringPinRetainerPinIron, "assaultFiringPinRetainerPinIron");
		GameRegistry.registerItem(assaultFiringPinRetainerPinBronze, "assaultFiringPinRetainerPinBronze");
		GameRegistry.registerItem(assaultFiringPinRetainerPinTitanium, "assaultFiringPinRetainerPinTitanium");
		GameRegistry.registerItem(assaultFiringPinRetainerPinAluminium, "assaultFiringPinRetainerPinAluminium");
		GameRegistry.registerItem(assaultFiringPinRetainerPinSteel, "assaultFiringPinRetainerPinSteel");
		GameRegistry.registerItem(assaultFiringPinRetainerPinPolymer, "assaultFiringPinRetainerPinPolymer");
		GameRegistry.registerItem(assaultFiringPinRetainerPinMythian, "assaultFiringPinRetainerPinMythian");
		GameRegistry.registerItem(assaultFiringPinRetainerPinPromethium, "assaultFiringPinRetainerPinPromethium");
		GameRegistry.registerItem(assaultFiringPinRetainerPinSarinum, "assaultFiringPinRetainerPinSarinum");
		GameRegistry.registerItem(assaultFiringPinRetainerPinVelerium, "assaultFiringPinRetainerPinVelerium");
		GameRegistry.registerItem(assaultFiringPinRetainerPinCelibras, "assaultFiringPinRetainerPinCelibras");
		GameRegistry.registerItem(assaultFiringPinRetainerPinAericas, "assaultFiringPinRetainerPinAericas");
		GameRegistry.registerItem(assaultFiringPinRetainerPinDarisin, "assaultFiringPinRetainerPinDarisin");

		GameRegistry.registerItem(assaultPistonChamberGold, "assaultPistonChamberGold");
		GameRegistry.registerItem(assaultPistonChamberIron, "assaultPistonChamberIron");
		GameRegistry.registerItem(assaultPistonChamberBronze, "assaultPistonChamberBronze");
		GameRegistry.registerItem(assaultPistonChamberTitanium, "assaultPistonChamberTitanium");
		GameRegistry.registerItem(assaultPistonChamberAluminium, "assaultPistonChamberAluminium");
		GameRegistry.registerItem(assaultPistonChamberSteel, "assaultPistonChamberSteel");
		GameRegistry.registerItem(assaultPistonChamberPolymer, "assaultPistonChamberPolymer");
		GameRegistry.registerItem(assaultPistonChamberMythian, "assaultPistonChamberMythian");
		GameRegistry.registerItem(assaultPistonChamberPromethium, "assaultPistonChamberPromethium");
		GameRegistry.registerItem(assaultPistonChamberSarinum, "assaultPistonChamberSarinum");
		GameRegistry.registerItem(assaultPistonChamberVelerium, "assaultPistonChamberVelerium");
		GameRegistry.registerItem(assaultPistonChamberCelibras, "assaultPistonChamberCelibras");
		GameRegistry.registerItem(assaultPistonChamberAericas, "assaultPistonChamberAericas");
		GameRegistry.registerItem(assaultPistonChamberDarisin, "assaultPistonChamberDarisin");
		
		GameRegistry.registerItem(assaultSpringGold, "assaultSpringGold");
		GameRegistry.registerItem(assaultSpringIron, "assaultSpringIron");
		GameRegistry.registerItem(assaultSpringBronze, "assaultSpringBronze");
		GameRegistry.registerItem(assaultSpringTitanium, "assaultSpringTitanium");
		GameRegistry.registerItem(assaultSpringAluminium, "assaultSpringAluminium");
		GameRegistry.registerItem(assaultSpringSteel, "assaultSpringSteel");
		GameRegistry.registerItem(assaultSpringPolymer, "assaultSpringPolymer");
		GameRegistry.registerItem(assaultSpringMythian, "assaultSpringMythian");
		GameRegistry.registerItem(assaultSpringPromethium, "assaultSpringPromethium");
		GameRegistry.registerItem(assaultSpringSarinum, "assaultSpringSarinum");
		GameRegistry.registerItem(assaultSpringVelerium, "assaultSpringVelerium");
		GameRegistry.registerItem(assaultSpringCelibras, "assaultSpringCelibras");
		GameRegistry.registerItem(assaultSpringAericas, "assaultSpringAericas");
		GameRegistry.registerItem(assaultSpringDarisin, "assaultSpringDarisin");
		
		GameRegistry.registerItem(assaultPistonGold, "assaultPistonGold");
		GameRegistry.registerItem(assaultPistonIron, "assaultPistonIron");
		GameRegistry.registerItem(assaultPistonBronze, "assaultPistonBronze");
		GameRegistry.registerItem(assaultPistonTitanium, "assaultPistonTitanium");
		GameRegistry.registerItem(assaultPistonAluminium, "assaultPistonAluminium");
		GameRegistry.registerItem(assaultPistonSteel, "assaultPistonSteel");
		GameRegistry.registerItem(assaultPistonPolymer, "assaultPistonPolymer");
		GameRegistry.registerItem(assaultPistonMythian, "assaultPistonMythian");
		GameRegistry.registerItem(assaultPistonPromethium, "assaultPistonPromethium");
		GameRegistry.registerItem(assaultPistonSarinum, "assaultPistonSarinum");
		GameRegistry.registerItem(assaultPistonVelerium, "assaultPistonVelerium");
		GameRegistry.registerItem(assaultPistonCelibras, "assaultPistonCelibras");
		GameRegistry.registerItem(assaultPistonAericas, "assaultPistonAericas");
		GameRegistry.registerItem(assaultPistonDarisin, "assaultPistonDarisin");
		
		GameRegistry.registerItem(assaultGasChamberGold, "assaultGasChamberGold");
		GameRegistry.registerItem(assaultGasChamberIron, "assaultGasChamberIron");
		GameRegistry.registerItem(assaultGasChamberBronze, "assaultGasChamberBronze");
		GameRegistry.registerItem(assaultGasChamberTitanium, "assaultGasChamberTitanium");
		GameRegistry.registerItem(assaultGasChamberAluminium, "assaultGasChamberAluminium");
		GameRegistry.registerItem(assaultGasChamberSteel, "assaultGasChamberSteel");
		GameRegistry.registerItem(assaultGasChamberPolymer, "assaultGasChamberPolymer");
		GameRegistry.registerItem(assaultGasChamberMythian, "assaultGasChamberMythian");
		GameRegistry.registerItem(assaultGasChamberPromethium, "assaultGasChamberPromethium");
		GameRegistry.registerItem(assaultGasChamberSarinum, "assaultGasChamberSarinum");
		GameRegistry.registerItem(assaultGasChamberVelerium, "assaultGasChamberVelerium");
		GameRegistry.registerItem(assaultGasChamberCelibras, "assaultGasChamberCelibras");
		GameRegistry.registerItem(assaultGasChamberAericas, "assaultGasChamberAericas");
		GameRegistry.registerItem(assaultGasChamberDarisin, "assaultGasChamberDarisin");
		
		GameRegistry.registerItem(assaultGasFeedGold, "assaultGasFeedGold");
		GameRegistry.registerItem(assaultGasFeedIron, "assaultGasFeedIron");
		GameRegistry.registerItem(assaultGasFeedBronze, "assaultGasFeedBronze");
		GameRegistry.registerItem(assaultGasFeedTitanium, "assaultGasFeedTitanium");
		GameRegistry.registerItem(assaultGasFeedAluminium, "assaultGasFeedAluminium");
		GameRegistry.registerItem(assaultGasFeedSteel, "assaultGasFeedSteel");
		GameRegistry.registerItem(assaultGasFeedPolymer, "assaultGasFeedPolymer");
		GameRegistry.registerItem(assaultGasFeedMythian, "assaultGasFeedMythian");
		GameRegistry.registerItem(assaultGasFeedPromethium, "assaultGasFeedPromethium");
		GameRegistry.registerItem(assaultGasFeedSarinum, "assaultGasFeedSarinum");
		GameRegistry.registerItem(assaultGasFeedVelerium, "assaultGasFeedVelerium");
		GameRegistry.registerItem(assaultGasFeedCelibras, "assaultGasFeedCelibras");
		GameRegistry.registerItem(assaultGasFeedAericas, "assaultGasFeedAericas");
		GameRegistry.registerItem(assaultGasFeedDarisin, "assaultGasFeedDarisin");
		
		GameRegistry.registerItem(assaultChamberGold, "assaultChamberGold");
		GameRegistry.registerItem(assaultChamberIron, "assaultChamberIron");
    	GameRegistry.registerItem(assaultChamberBronze, "assaultChamberBronze");
    	GameRegistry.registerItem(assaultChamberTitanium, "assaultChamberTitanium");
    	GameRegistry.registerItem(assaultChamberAluminium, "assaultChamberAluminium");
    	GameRegistry.registerItem(assaultChamberSteel, "assaultChamberSteel");
    	GameRegistry.registerItem(assaultChamberPolymer, "assaultChamberPolymer");
    	GameRegistry.registerItem(assaultChamberMythian, "assaultChamberMythian");
    	GameRegistry.registerItem(assaultChamberPromethium, "assaultChamberPromethium");
    	GameRegistry.registerItem(assaultChamberSarinum, "assaultChamberSarinum");
    	GameRegistry.registerItem(assaultChamberVelerium, "assaultChamberVelerium");
    	GameRegistry.registerItem(assaultChamberCelibras, "assaultChamberCelibras");
    	GameRegistry.registerItem(assaultChamberAericas, "assaultChamberAericas");
    	GameRegistry.registerItem(assaultChamberDarisin, "assaultChamberDarisin");
    	
    	GameRegistry.registerItem(assaultReceiverM4Gold, "assaultReceiverM4Gold");
		GameRegistry.registerItem(assaultReceiverM4Iron, "assaultReceiverM4Iron");
    	GameRegistry.registerItem(assaultReceiverM4Bronze, "assaultReceiverM4Bronze");
    	GameRegistry.registerItem(assaultReceiverM4Titanium, "assaultReceiverM4Titanium");
    	GameRegistry.registerItem(assaultReceiverM4Aluminium, "assaultReceiverM4Aluminium");
    	GameRegistry.registerItem(assaultReceiverM4Steel, "assaultReceiverM4Steel");
    	GameRegistry.registerItem(assaultReceiverM4Polymer, "assaultReceiverM4Polymer");
    	GameRegistry.registerItem(assaultReceiverM4Mythian, "assaultReceiverM4Mythian");
    	GameRegistry.registerItem(assaultReceiverM4Promethium, "assaultReceiverM4Promethium");
    	GameRegistry.registerItem(assaultReceiverM4Sarinum, "assaultReceiverM4Sarinum");
    	GameRegistry.registerItem(assaultReceiverM4Velerium, "assaultReceiverM4Velerium");
    	GameRegistry.registerItem(assaultReceiverM4Celibras, "assaultReceiverM4Celibras");
    	GameRegistry.registerItem(assaultReceiverM4Aericas, "assaultReceiverM4Aericas");
    	GameRegistry.registerItem(assaultReceiverM4Darisin, "assaultReceiverM4Darisin");
    	
    	GameRegistry.registerItem(assaultFrontEndM4Gold, "assaultFrontEndM4Gold");
		GameRegistry.registerItem(assaultFrontEndM4Iron, "assaultFrontEndM4Iron");
    	GameRegistry.registerItem(assaultFrontEndM4Bronze, "assaultFrontEndM4Bronze");
    	GameRegistry.registerItem(assaultFrontEndM4Titanium, "assaultFrontEndM4Titanium");
    	GameRegistry.registerItem(assaultFrontEndM4Aluminium, "assaultFrontEndM4Aluminium");
    	GameRegistry.registerItem(assaultFrontEndM4Steel, "assaultFrontEndM4Steel");
    	GameRegistry.registerItem(assaultFrontEndM4Polymer, "assaultFrontEndM4Polymer");
    	GameRegistry.registerItem(assaultFrontEndM4Mythian, "assaultFrontEndM4Mythian");
    	GameRegistry.registerItem(assaultFrontEndM4Promethium, "assaultFrontEndM4Promethium");
    	GameRegistry.registerItem(assaultFrontEndM4Sarinum, "assaultFrontEndM4Sarinum");
    	GameRegistry.registerItem(assaultFrontEndM4Velerium, "assaultFrontEndM4Velerium");
    	GameRegistry.registerItem(assaultFrontEndM4Celibras, "assaultFrontEndM4Celibras");
    	GameRegistry.registerItem(assaultFrontEndM4Aericas, "assaultFrontEndM4Aericas");
    	GameRegistry.registerItem(assaultFrontEndM4Darisin, "assaultFrontEndM4Darisin");
    	
    	GameRegistry.registerItem(assaultStockM4Gold, "assaultStockM4Gold");
		GameRegistry.registerItem(assaultStockM4Iron, "assaultStockM4Iron");
    	GameRegistry.registerItem(assaultStockM4Bronze, "assaultStockM4Bronze");
    	GameRegistry.registerItem(assaultStockM4Titanium, "assaultStockM4Titanium");
    	GameRegistry.registerItem(assaultStockM4Aluminium, "assaultStockM4Aluminium");
    	GameRegistry.registerItem(assaultStockM4Steel, "assaultStockM4Steel");
    	GameRegistry.registerItem(assaultStockM4Polymer, "assaultStockM4Polymer");
    	GameRegistry.registerItem(assaultStockM4Mythian, "assaultStockM4Mythian");
    	GameRegistry.registerItem(assaultStockM4Promethium, "assaultStockM4Promethium");
    	GameRegistry.registerItem(assaultStockM4Sarinum, "assaultStockM4Sarinum");
    	GameRegistry.registerItem(assaultStockM4Velerium, "assaultStockM4Velerium");
    	GameRegistry.registerItem(assaultStockM4Celibras, "assaultStockM4Celibras");
    	GameRegistry.registerItem(assaultStockM4Aericas, "assaultStockM4Aericas");
    	GameRegistry.registerItem(assaultStockM4Darisin, "assaultStockM4Darisin");
	}
}
